#!bash
# ==========================================================================================
# Copyright (C) 2022 Richard DJE
#
# This file is part of simenv
#
# simenv is free software: you can redistribute it and/or modify it under the terms
# of the GNU General Public License as published by the Free Software Foundation, either 
# version 3 of the License, or any later version.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along with this program. 
# If not, see <https://www.gnu.org/licenses/>.
# ==========================================================================================


# Function: main
#
function main
{
  if [[ $1 ]] && [[ -d $(get_subdir)/$1 ]]; then
    local _sub=$1
    shift
    
    callsub $(get_subdir)/$_sub "$@"
    return
  fi

  opt=$(getopt -a -n "$(get_subpath)" -oh -lhelp -- "$@")
  if (( $? && $? < 4)); then
    callsub $(get_subdir)/help
    exit 1
  fi

  eval set -- $opt

  local posid
  while (($#)); do
    case $1 in
      -h|--help)
          callsub $(get_subdir)/help 
          return
          ;;

      --) shift
          ;;

      *)  local pos[$((posid++))]=$1 
          shift
          ;;
    esac
  done


  set -- "${pos[@]}"        


  cat_dirlist | nl
}


main "$@"
