#!bash
# ==========================================================================================
# Copyright (C) 2022 Richard DJE
#
# This file is part of simenv
#
# simenv is free software: you can redistribute it and/or modify it under the terms
# of the GNU General Public License as published by the Free Software Foundation, either 
# version 3 of the License, or any later version.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along with this program. 
# If not, see <https://www.gnu.org/licenses/>.
# ==========================================================================================

# Function: usage
#
function usage
{
  cat <<USAGE | sed -r 's/simenv/\\e[1m&\\e[0m/; s/sub\w+/\\e[4m&\\e[0m/g' | sed 's/.*/echo -e "&"/e' 
usage: simenv subcmd [options] [arguments]
  
  subcommands:
    
$(
  for s in $(ls */main); do
    (
      callsub $s usage short
      # if [[ $(type -t usage) == function ]]; then usage short; fi
    )
  done
)
USAGE
  echo
}

function callsub
{
  local cwd=$PWD main=$1
  echo "$FUNCNAME: cwd<$cwd> main<$main>"
  shift
  source $main "$@" 
}

# Function: main
#
function main
{
  if (($#)); then
    dir=$(dirname $main)
    sub=$1
    shift
  
    if [[ -s $dir/$sub/main ]]; then
      (
        callsub $dir/$sub/main "$@"
      )
    else
      echo -e "\e[1;31m-E-\e[0m Unknown subcommand \e[1m$sub\e[0m\n"
      usage
    fi
  else
    usage
  fi
}


main "$@"
