#!/usr/bin/env bash
# ==========================================================================================
# Copyright (C) 2022 Richard DJE
#
# This file is part of simenv
#
# simenv is free software: you can redistribute it and/or modify it under the terms
# of the GNU General Public License as published by the Free Software Foundation, either 
# version 3 of the License, or any later version.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along with this program. 
# If not, see <https://www.gnu.org/licenses/>.
# ==========================================================================================

shopt -s extglob # globstar

rootdir=$(readlink -e $0 | xargs dirname)

function get_rootdir  { echo $rootdir; }
function get_cwd      { echo $cwd; }
function get_subdir   { eval "echo $(dirname $main) ${1:+| sed 's/\//\n/g' | head -n $1 | sed ':a; N;  $ {s/\n/\//g}; b a '}"; }
function get_local    { echo $(get_subdir $1)/.local; }
function get_run      { echo $(get_subdir $1)/.run; }
function callsub
{
  local main=$1/main
  if (( callsub )); then echo -e "\e[1;31m$FUNCNAME\e[0m: $main"; fi
  shift
  
  init_dirs
  push_subpath $(dirname $main | xargs basename)
  #echo "get_subdir<$(get_subdir)>" 
  #echo "get_subpath<$(get_subpath)>" 
  source $main "$@" 
  pop_subpath
}


# Function: init_dirs
#
function init_dirs
{
  mkdir -p $(get_local) $(get_run)
  cd $(get_run)
  #echo rm -f *
}

# Function: setvar
#
function setvar
{
  local setid
  while (($#)); do
    case $1 in
      -a) local append=1;
          shift
          ;;

      # Collect all positional arguments
      *)  local setpos[$((setid))]="$1"
          ((setid++))
          shift
          ;;
    esac
  done

  set -- "${setpos[@]}"

  if [[ $debug ]]; then echo "$FUNCNAME: #<$#> pos<${setpos[@]}> append<$append>" 1>&2; fi

  if (($# != 2)); then
    echo $FUNCNAME requires exactly two arguments: "<name> <value>"
    exit 1
  fi

  if [[ $debug ]]; then echo "$FUNCNAME: Setting $1 to '$2'" 1>&2; fi
  
  if ((append)); then
    echo "$2" >> $1
  else
    echo "$2" > $1
  fi
}

# Called inside sed s//.../e
export -f setvar

function clear_subpath  { truncate -s 0 $(get_rootdir)/.local/subpath; }
function push_subpath   { echo "$1"  >> $(get_rootdir)/.local/subpath; }
function pop_subpath    { echo "$(head -n -1 $(get_rootdir)/.local/subpath)" > $(get_rootdir)/.local/subpath; }
function get_subpath    { eval "cat $(get_rootdir)/.local/subpath ${1:+| head -n $1} | xargs"; }


clear_subpath

cwd=$PWD
callsub $rootdir "$@"
