#!bash
# ==========================================================================================
# Copyright (C) 2022 Richard DJE
#
# This file is part of simenv
#
# simenv is free software: you can redistribute it and/or modify it under the terms
# of the GNU General Public License as published by the Free Software Foundation, either 
# version 3 of the License, or any later version.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along with this program. 
# If not, see <https://www.gnu.org/licenses/>.
# ==========================================================================================


# Function: main
#
function main
{
  if (($#)); then return; fi

  cat <<USAGE | sed -r 's/simenv/\\e[1m&\\e[0m/; s/sub\w+/\\e[4m&\\e[0m/g' | sed 's/.*/echo -e "&"/e' 
usage: simenv subcmd [options] [arguments]
  
  subcommands:
    
$(
  for s in $(ls $(readlink -e $(get_cmdir)/../*/main)); do
    (
       callsub $s help short
    )
  done
)
USAGE
  echo
}


main "$@"
