#!bash
# ==========================================================================================
# Copyright (C) 2022 Richard DJE
#
# This file is part of simenv
#
# simenv is free software: you can redistribute it and/or modify it under the terms
# of the GNU General Public License as published by the Free Software Foundation, either 
# version 3 of the License, or any later version.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along with this program. 
# If not, see <https://www.gnu.org/licenses/>.
# ==========================================================================================


# Function: main
#
function main
{
  #if (($# == 0)); then
  #  callsub $(get_subdir)/help
  #  return
  #fi

  if (($#)); then
    if [[ -d $(get_subdir)/$1 ]]; then
      local _sub=$1
      shift
      
      callsub $(get_subdir)/$_sub "$@"
      return
    fi
  fi

  # Collect the options and positional arguments
  opts=$(getopt -a -n "$(get_subpath)" -oh,n,s -lhelp -- "$@")
  if (($? && $? < 4)); then
    callsub $(get_subdir)/help
    return
  fi


  eval set -- $opts

  local posid
  while (($#)); do
    case $1 in
      -h|--help)
          callsub $(get_subdir)/help 
          return
          ;;

      -n) local nonum=1
          shift
          ;;

      -s) local serial=1
          shift
          ;;

  # Insert your code here to add new options' handling

      --) shift;;

      *)  local pos[$((posid++))]=$1 
          shift
          ;;
    esac
  done



  eval find $(get_local -1) -maxdepth 1 -mindepth 1 -type d  -printf "\"%A@\t%f\n\"" '|' cut -f2  \
            $(if ((!nonum)); then echo '| nl -nln'; fi)                                           \
            $(if ((nonum && serial)); then echo '| xargs'; fi)

  #set - "${pos[@]}"

  #if (($# != 1)); then
  #  echo -e "\e[1;31m-E-\e[0m Missing list's name"
  #  callsub $(get_subdir)/help
  #  return
  #fi

  #local name=$1

  #if [[ -f $(get_local -1)/$name ]]; then
  #  cat $(get_local -1)/$name
  #else
  #  echo -e "\e[1;31m-E-\e[0m Unknown list \e[1m$name\e[0m"
  #fi
}


main "$@"
