#!bash

function _simenv_usage
{
  cat <<USAGE | sed -r 's/simenv/\\e[1m&\\e[0m/; s/sub\w+/\\e[4m&\\e[0m/g' | sed 's/.*/echo -e "&"/e' 
usage: simenv subcmd [options] [arguments]
  
  subcommands:
    
$(
  for s in $(ls $SUB_DIR); do
    (
      source $s
      if [[ $(type -t usage) == function ]]; then usage short; fi
    )
  done
)
USAGE
  echo
}

if (($#)); then
  cmd=$1
  shift

  if [[ -s $SUB_DIR/$cmd ]]; then
    export DOT=$DOT_TOP/$cmd

    source $cmd

    mkdir -p $DOT 

    if [[ $(type -t _$cmd) == function ]]; then
      _$cmd "$@"
    else
      echo -e "\e[1;31m-E-\e[0m Main function not found for subcommand \e[1m$cmd\e[0m"
    fi
  else
    echo -e "\e[1;31m-E-\e[0m Unknown subcommand \e[1m$cmd\e[0m\n"
    _simenv_usage
  fi
else
  _simenv_usage
fi
