#!bash

for sub in $(ls $SUB_DIR); do
  if ((debug)); then echo sourcing $sub; fi

  _cdot=${sub}_dot
  _ctpl=${sub}_tpl

  export $_cdot=$DOT_TOP/$sub
  export $_ctpl=$TPL_TOP/$sub

  mkdir -p ${!_cdot} ${!_ctpl}

  source $sub
done
