#!bash
# ==========================================================================================
# Copyright (C) 2022 Richard DJE
#
# This file is part of simenv
#
# simenv is free software: you can redistribute it and/or modify it under the terms
# of the GNU General Public License as published by the Free Software Foundation, either 
# version 3 of the License, or any later version.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along with this program. 
# If not, see <https://www.gnu.org/licenses/>.
# ==========================================================================================


# Function: main
#
function main
{
  if (($# == 0)); then
    callsub help
    return 
  fi

  if [[ -d $(get_subdir)/$1 ]]; then
    callsub "$@"
    return
  fi

  opt=$(getopt -a -n "$(get_subpath)" -oh -lhelp -- "$@")
  if (( $? && $? < 4)); then
    callsub help
    exit 1
  fi

  eval set -- $opt

  local pos posid
  while (($#)); do
    case $1 in
      -h|--help)
          callsub help 
          return
          ;;

      --) shift;;

      *)  pos[$((posid++))]=$1 
          shift
          ;;
    esac
  done


  set -- "${pos[@]}"


  set_var maxid 0
  eval num_names=($(grep -o '\S\+' <<<"$@" | sed 's/=/ /' | while read id va; do
      if ((id > $(<maxid))); then
        set_var maxid $id
        
        if [[ $debug ]]; then echo $FUNCNAME: new max is $(<maxid) 1>&2; fi
      fi

      echo "[$id]=$va"
    done
  ))


  dirlist=`cat_dirlist | nl -nln | while read linenum name_path; do
    name=$(grep -o '^\w\+' <<<$name_path)
    path=$(grep -o '/.*$'  <<<$name_path)

    if [[ ${num_names[$linenum]} ]]; then
      #if [[ $name_path =~ ^/ ]]; then
      #  printf "\tNo name attached yet, \e[1m${num_names[$linenum]}\e[0m will be applied" 
      #else
      #  printf "\tCurrent name will be replaced" 
      #fi
      
      printf "%-8s%s\n\n" "${num_names[$linenum]}" $path
    else
      printf "%-8s%s\n\n" "$name" $path
    fi 
  done`

  echo "$dirlist" | tee $(get_dirlist) | nl
}


main "$@"
