#!bash
# ==========================================================================================
# Copyright (C) 2022 Richard DJE
#
# This file is part of simenv
#
# simenv is free software: you can redistribute it and/or modify it under the terms
# of the GNU General Public License as published by the Free Software Foundation, either 
# version 3 of the License, or any later version.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along with this program. 
# If not, see <https://www.gnu.org/licenses/>.
# ==========================================================================================


# Function: main
#
function main
{
  if (($# == 0)); then
    callsub help
    return 
  fi

  if [[ -d $(get_subdir)/$1 ]]; then
    callsub "$@"
    return
  fi

  opt=$(getopt -a -n "$(get_subpath)" -oh -lhelp -- "$@")
  if (( $? && $? < 4)); then
    callsub help
    exit 1
  fi

  eval set -- $opt

  local pos posid
  while (($#)); do
    case $1 in
      -h|--help)
          callsub help 
          return
          ;;

      --) shift
          ;;

      *)  pos[$((posid++))]=$1 
          shift
          ;;
    esac
  done


  set -- "${pos[@]}"

  if (($# > 2)); then
    printf "\e[1;31m-E-\e[0m Too many positional arguments (max=2)\n"
    callsub help
    return 
  fi

  id=$1
  down=${2:-1}

  filtered=$(cat_dirlist | nl -nln | if [[ $id =~ ^[[:alpha:]] ]]; then
      sed -r '/\s+'$id'\s.*/ {s/.*/set_var  selected "&"/e; d}'
    else
      sed -r '/^'$id'\s+.*/  {s/.*/set_var  selected  "&"/e; d}'
    fi
  )

  if [[ ! -f selected ]]; then
    printf "\e[1;31m-W-\e[0m No match\n"
    return
  fi

  cpos=$(grep -o '^[[:digit:]]\+' selected)
  npos=$((cpos + down))
  dirlist_lcnt=$(wc -l $(get_dirlist) | cut -d' ' -f1)
  if ((npos >= $dirlist_lcnt)); then
    npos=$dirlist_lcnt
  fi

  #echo "cpos<$cpos> --> npos<$npos>"
  echo "$filtered" | sed -r '/^'$npos'/a'"$(<selected)" | sed -r 's/^.*\s+([[:alpha:]].*)/\1/' | tee $(get_dirlist) | nl
}


main "$@"
