#!bash
# ==========================================================================================
# Copyright (C) 2022 Richard DJE
#
# This file is part of simenv
#
# simenv is free software: you can redistribute it and/or modify it under the terms
# of the GNU General Public License as published by the Free Software Foundation, either 
# version 3 of the License, or any later version.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along with this program. 
# If not, see <https://www.gnu.org/licenses/>.
# ==========================================================================================


# Function: usage
#
function usage
{
  :
}


# Function: main N|name [D=1]
#
function main
{
  #echo "$FUNCNAME: <$#> <$@>"
  if (($# == 0 || $# > 2)); then
    echo  "usage: simenv grep down N|name [U=1]" | sed -r 's/-E-/\\\\e[1;31m&\\\\e[0m/; s/down/\\\\e[1m&\\\\e[0m/; s/N|name|U/\\\\e[4m&\\\\e[0m/g' | xargs echo -e
    return 
  fi

  id=$1
  down=${2:-1}

  filtered=$(cat_dirlist | nl -nln | if [[ $id =~ ^[[:alpha:]] ]]; then
      sed -r '/\s+'$id'\s.*/ {s/.*/setvar  selected "&"/e; d}'
    else
      sed -r '/^'$id'\s+.*/  {s/.*/setvar  selected  "&"/e; d}'
    fi
  )

  cpos=$(grep -o '^[[:digit:]]\+' selected)
  npos=$((cpos + down))
  dirlist_lcnt=$(wc -l $(get_dirlist) | cut -d' ' -f1)
  if ((npos >= $dirlist_lcnt)); then
    npos=$dirlist_lcnt
  fi

  #echo "cpos<$cpos> --> npos<$npos>"
  echo "$filtered" | sed -r '/^'$npos'/a'"$(<selected)" | sed -r 's/^.*\s+([[:alpha:]].*)/\1/' | tee $(get_dirlist) | nl
}


main "$@"
