#!bash
# ==========================================================================================
# Copyright (C) 2022 Richard DJE
#
# This file is part of simenv
#
# simenv is free software: you can redistribute it and/or modify it under the terms
# of the GNU General Public License as published by the Free Software Foundation, either 
# version 3 of the License, or any later version.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along with this program. 
# If not, see <https://www.gnu.org/licenses/>.
# ==========================================================================================


# Function: main
#
function main
{
  if (($# == 0)); then
    callsub $(get_subdir)/help
    return
  fi

  if [[ -d $(get_subdir)/$1 ]]; then
    local _sub=$1
    shift
    
    callsub $(get_subdir)/$_sub "$@"
    return
  fi

  # Collect the options and positional arguments
  opts=$(getopt -a -oh,d:,n,v -lhelp -- "$@")
  if (($? && $? < 4)); then
    callsub $(get_subdir)/help
    return
  fi


  eval set -- $opts

  local posid
  while (($#)); do
    case $1 in
      -h|--help)
          callsub $(get_subdir)/help 
          return
          ;;

      -d) local directory=$2
          shift 2
          ;;

      -n) local dryrun=1
          shift
          ;;

      -v) local verbose=1
          shift
          ;;

      --) shift
          ;;

      *)  local pos[$((posid++))]=$1 
          shift
          ;;
    esac
  done


  set -- "${pos[@]}"

  if [[ $directory ]]; then
    if [[ -d $directory ]]; then
      cd $directory
    else
      echo -e "\e[1;31m-E-\e[0m Cannot access directory '\e[1m$directory\e[0m'"
    fi
  else
    cd $(get_cwd)
  fi


  for p; do
    mkdir -vp $p/help 
    add_main $p/help
  done
}

# Function: add_main
#
function add_main
{
  local path=$1

  #echo "$FUNCNAME: $path"

  if [[ -d $path ]]; then
    local base=$(basename $path)

    if [[ ! -s $path/main ]]; then
      if [[ $base == help ]]; then
        cp $(get_subdir)/help.tpl $path/main
      else
        cp $(get_subdir)/sub.tpl  $path/main
      fi
    fi

    local dir=$(dirname $path)
    
    if [[ $dir != . ]]; then
      add_main $dir
    fi
  else
    echo -e "\e[1;31m-W-\e[0m Cannot access path '\e[1m$path\e[0m'"
  fi
}


main "$@"
